class Event:
    COMPETITIONS_STATE_CHANGE = "COMPETITIONS_STATE_CHANGE"
    NEW_USER_IN_PLACE = "NEW_USER_IN_PLACE"

    FETCH_USER_COUNT = "FETCH_USER_COUNT"
    FETCH_USERS_IN_PLACE = "FETCH_USERS_IN_PLACE"

